sudo: required
dist: trusty

language: node_js
node_js: "5.1"

services:
  docker

git:
  submodules: false

before_install:
  - id
  - docker pull rainbeam/dapple
  - docker images
  - cp .travis.dapplerc $HOME/.dapplerc
  - git submodule update --init --recursive
  - npm install

script:
  - ./.travis.dapple-docker-entry test
  - npm test
